### ISSUE TITLE
Discord mention parsing is greedy

### ISSUE THREAD

**Issue by DanielRX** [Supinic/supibot#21]
Context: 
Within a discord server that has a member with username `13#XXXX`

If I do `$remind discordUser in 30s Hello` and their discord id is: `13XXXXXXXXXXXXXXXX`, when the command resolves, it will ping the `13#XXXX` user, not the user I targeted with `$remind` (the `discordUser`)

**Comment by Supinic** [comment]
If I understand this correctly, this is the sequence of steps you're describing:
- 1. user A discord ID is e.g. `13xxx`
- 2. user B's discord name is `13#tag`
- 3. `$remind (user A) hello`
- 4. When the reminder is received, the mention in that reminder does not target user A, but rather user B - seemingly because of the mimatch between the name and the ID

If this is correct, I would appreciate if both those users would join my Discord server, so I can simulate this behaviour

**Comment by Supinic** [comment]
After a brief demonstration, I figured out what is wrong:

https://github.com/Supinic/supibot/blob/18605ce27b9b1c2595c6578e8c533318f041b60e/controllers/discord.js#L276

A fired reminder will attempt to ping a user by establishing a mention in the `<@(user-id)>` format. When attempting to send the message however, the abovementioned regex replaces the internals of the mention - by not checking for a preceding `<` character.

**Comment by Supinic** [comment]
Fixed in c678672 - forgot to link commit with this issue
