### ISSUE TITLE
The `data.Origin` setup script fails because of foreign key contraints

### ISSUE THREAD

**Issue by Wissididom** [Supinic/supibot#50]
When I tried to get `$origin` to work (which I still didn't get to work because I think I first need to run a few `INSERT`s I think) I found that the [SQL-Command](https://github.com/Supinic/supibot/blob/master/commands/origin/origin.sql) does not work because of the foreign key constraints. I fixed that by changing `Raffle_Winner`, `Author` and `User_Alias` from `INT(11)` to `INT(10) UNSIGNED` on my instance because `chat_data.User_Alias.ID` does have that type.

To debug that I ran that command without the constraints and added those later with `ALTER TABLE data.Origin ADD CONSTRAINT [...]`.

**Comment by Supinic** [comment]
Thanks! `User_Alias.ID` is defined as `INT(10) UNSIGNED` in the scripts, however in my instance it is `INT(11)` (signed) because it was established way back without an easy way to refactor. So when I export SQL definitions, the ID type I use sneaks out sometimes instead of the proper one for public use!
